application: learn-cryptography
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  login: admin
  static_dir: static

- url: /resetdata
  login: admin
  script: reset.app

- url: .*
  login: admin
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest
